### ISSUE TITLE
User gets confirmation that their contribution has been saved.

### ISSUE THREAD

**Issue by derekrazo** [open-app/cobudget#43]
Currently the app goes all green to indicate that the user has completed their allocation. We've gotten tons of user feedback indicating that people want a much more satisfying confirmation.

Contributor should get some type of summary of their contributions, and a message reassuring them that their contributions have been saved.

**Comment by jonlemmon** [comment]
![screenshot 2015-01-27 18 25 29](https://cloud.githubusercontent.com/assets/1179717/5914056/33ec0f14-a653-11e4-806d-6a88ce5148b4.png)

@ahdinosaur see above for the various contribution save states. Clicking away will also save. Pressing Esc will cancel and return to the old value you typed in (or back to "Fund") if you never had a contribution before.

Also note that I've removed the up/down arrows on the right.

**Comment by jonlemmon** [comment]
@ahdinosaur hovering over "Fund" button should invert the colors (so like the styling of the filled in $250 button). Hovering over the filled in orange button should make the color go slightly darker.

**Comment by derekrazo** [comment]
Need to add new designs (grey)

**Comment by derekrazo** [comment]
Ticket was bigger than we thought.

**Comment by derekrazo** [comment]
I notice that there is no estimate on this card? @jonlemmon @ahdinosaur
