### ISSUE TITLE
Contribution buttons / allocation boxes should be easy to use.

### ISSUE THREAD

**Issue by derekrazo** [open-app/cobudget#50]
Currently the contribution process (click into a number box and push up / down or type a number ) is a bit janky. 

This process should be made more intuitive.

**Comment by ahdinosaur** [comment]
is this resolved now with the work done on https://github.com/open-app/cobudget/issues/43, or should we keep it open for a more complete redesign?

**Comment by derekrazo** [comment]
I reckon its good to close!
