### ISSUE TITLE
User sees feedback on whether their updates have saved or failed

### ISSUE THREAD

**Issue by ahdinosaur** [open-app/cobudget#54]
the UI updates optimistically in that the user interface updates before the API is updated, plus we currently have little to no error handling for when API updates fail. this needs some love.

this leads to the following:

> I am experiencing a bug which causes contribution amounts to disapear
on the contributors screen. It may be when a new user is added -
previous user's contribution amounts get wiped, reassigned or
something.   For example, I added 5 new contributors and allocate 67.81
each.  I then added S, R, L, A. They should
have all shown as 0 allocation.  Instead they had 67.81 and the 5 new
contributors had been reset to 0.
> 
> It's random. Sometimes only some contributor totals change. Then
I had every figure I put in wiped when I returned to the screen.
Extremely frustrating. Hopefully the figures will stick for this round -
I'm going to avoid editing them while the round is active.
> 
> ...
>
> From my perspective they all saved just fine. Then I left the screen and came back and everything changed. This happened 5-6 times. Sometimes just a few values changed, but this morning every allocation in the S round was wiped out when I came back to it a few mins later :( Let me know if there's anything I can do to help test. Suggest a different Group though - I don't want to accidentally mess up the current S / F rounds by visiting the allocations page right now (just in case).

it'd be great to have a consistent design for how to display this feedback (saving, saved, save failed) to the user across all our inputs. once upon a time i remember seeing a cool component with a green spinner for saving, green checkmark for saved, and red x for save failed, but i can't find it again.

**Comment by jonlemmon** [comment]
When a resource is saving, the text should go grey, and then black when it's saved.

If an error is unhandleable: pop up a modal and revert the unsaved content edit mode.

**Comment by ahdinosaur** [comment]
btw, this has only been implemented in the contribution input.

remaining (off the top of my head):
- [ ] group members input
- [ ] allocation input
