### ISSUE TITLE
Sponsor cannot delete or edit buckets in open or closed rounds.

### ISSUE THREAD

**Issue by derekrazo** [open-app/cobudget#61]

**Comment by ahdinosaur** [comment]
this is done in the UI.

**Comment by derekrazo** [comment]
I notice that there is no estimate on this card? @jonlemmon @ahdinosaur

**Comment by jonlemmon** [comment]
@ahdinosaur @derekrazo just thinking through the logic of this. Here's how it is on the front-end:

```
if group.isAdmin(currentUser) or
    (
      round.status.name == 'pending' and
      round.membersCanProposeBuckets and
        $scope.bucket.user.id == currentUser.id
    )
```

This means that admins can edit closed rounds. Is this what we want? My assumption is that we want:

- Admins can edit/delete buckets while round is pending/open
- Bucket sponsors can edit/delete their own buckets while round is pending

This sound right to you guys?

**Comment by derekrazo** [comment]
@jonlemmon - that sounds sweet :)

The only thing I'm not sure about is Admins editing / deleting buckets while round is open. I'm of two minds on it - one is that it's problematic to have the admins be able to edit delete while allocations are happening when no can see a log of the admins activity. On the other hand it seems prudent to err on the side of trusting the admins for now.

After writing that I think it's sweet to give admins those powers.
