### ISSUE TITLE
Members not showing up in contributor list - admin cannot give allocations

### ISSUE THREAD

**Issue by derekrazo** [open-app/cobudget#74]
![screen shot 2015-02-09 at 10 43 47 am](https://cloud.githubusercontent.com/assets/3849179/6098580/94b5f05e-b048-11e4-8cdf-2d85b144c3a3.png)

If you look at the current foundation round, it looks like this. Not sure what's up. I'm not getting any errors.

**Comment by ahdinosaur** [comment]
this is [expected behavior](https://github.com/open-app/cobudget-ui/blob/master/src/node_modules/round-contributors/round-contributors-controller.coffee#L13-L15), as non-admins shouldn't see contributors with no allocations.
