### ISSUE TITLE
Admin adds member to group by email from members page. (no invite)

### ISSUE THREAD

**Issue by derekrazo** [open-app/cobudget#75]
I need to be able to add people by email to members lists of a group. Tying this up with invitations has pushed this back for over a month and it's a real source of time wasting for me. It seems to me that this shouldn't interfere with the other cards and is a relatively easier job.

I've moved it to the ready list. 

Can I please get some feedback / an estimate on this? @jonlemmon @ahdinosaur

**Comment by jonlemmon** [comment]
Cool makes sense. From the API perspective:

1. Admin adds email address to group
2. If email is already associated with an account, they are added to group
3. If no account is found, account is created with a random password, added to the group, and the user is emailed their temporary password and a link to visit the group.

I'd give this a 2 (~1 day of work) for the API.

**Comment by ahdinosaur** [comment]
in the UI,

1. admin enters email address into form
2. admin submits form (which sends a `POST /memberships` request to server, which responds with the created membership object. the new membership is added to the groups memberships as before.)

1. existing user logs in normally.

1. new user logs in and since `force_password_reset == true`, the change password prompt opens.

i reckon this is a 1 (~0.5 day of work) for the UI.

**Comment by ahdinosaur** [comment]
@jonlemmon here's what i'm thinking for `POST /memberships`:
```
{
  group_id: 1,
  member: {
    email: "person@stuff.com"
  }
}
```

which should return with
```
{
  group_id: 1,
  member: {
    id: 42
  }
}
```

email could be included in the output too, that's related to #65.

are you thinking the same or something else? :tangerine:

**Comment by ahdinosaur** [comment]
@jonlemmon and i talked about some changes to new user login:

1. new user logs in and since `initialized == false`, a dialog opens that requests the user to update their profile information.

add another 1 (~0.5 day of work) to the UI.

**Comment by jonlemmon** [comment]
This is deployed!!

Hey @ahdinosaur, here's some small changes that I think should be made to the UI. The first two are the most important:

- Button and form should go into disabled state while sending invite
- Server error should display server error modal
- Cancel button should be removed
- Clicking outside the modal should close it (instead of popping up another weird modal)

**Comment by jonlemmon** [comment]
Also, @ahdinosaur and @derekrazo, right now all the mail is coming from noreply@cobudget.co.

For deliverability reasons, it has to come from a cobudget.co address. Are we able to hook cobudget.co up to our Enspiral mail account? Then we can make all the noreply emails forward to derek or something. :hear_no_evil:

**Comment by derekrazo** [comment]
Cobudget is already just an alias for an enspiral email address. I'm not
sure about how to do this, but I'll ask around a bit!

Awesome stuff :)
ᐧ

**Comment by getresults** [comment]
@jonlemmon @derekrazo - I can help with this. I'll see if I can get set up for you today.

**Comment by getresults** [comment]
We can currently set up aliases from any @cobudget.co email address to an Enspiral email address.

I've just called Google Apps support who have confirmed that we can only have a catchall address on the main Enspiral domain.  We can't have separate catchall addresses on any of the secondary domains added to this account. 

So our options are: 

1) Add any additional @cobudget.co aliases to redirect to one or more @enspiral.com email addresses. No cost. 

2) Add one or more email accounts @cobudget.co under the Enspiral Google Apps account.  This would give us a cobudget.co email address we can send from (contact@cobudget.co for example).  However we can't set up a catchall address for the @cobudget.co domain.  Catch-all emails will end up in the @ensprial.com catchall account.  Cost:  US$50 / email address / year. 

3) Create an entirely separate Google Apps Admin account for cobudget.co.  This would give us an outgoing email address and allow the set up of a catchall address for cobudget.co.  Cost: US$50 / user / year.    Disadvantages:  @cobudget.co accounts won't have access to Enspiral's Google Drive (unless files / folders are shared) and requires separate Google Apps administration.

**Comment by getresults** [comment]
Actually we might be able to set up a catch-all with our existing Enspiral Google Apps account using this work around: https://productforums.google.com/forum/#%21topic/apps/zjgh6pEMCXk.   Can test later on...

**Comment by jonlemmon** [comment]
Great thanks Phill! Can we set up noreply@coboduget.co to Derek's Enspiral
account?

**Comment by getresults** [comment]
Done!

**Comment by jonlemmon** [comment]
Thanks!!
