### ISSUE TITLE
migrate open-app/cobudget-* repos to cobudget org

### ISSUE THREAD

**Issue by ahdinosaur** [open-app/cobudget#76]
i propose we migrate the `cobudget-*` repos from the `open-app` org to the `cobudget` org, which means this top-level repo stays here. the reasoning is that it's nice to have all the repos related to a project in one org (including when we fork other repos for use in our project), but i'd rather we not pollute the shared org of `open-app` (which i see as a place where many independent projects can put their top-level repos, thus building a network of projects connected together in spirit).

how do we feel about this @derekrazo @jonlemmon @joshuavial?

**Comment by derekrazo** [comment]
Sounds good to me - go for it I reckon
ᐧ

**Comment by joshuavial** [comment]
+1 for each app just having a top level repo in the open-app org - I think
we could also just have an open-app/core repo which links to the orgs of
the projects which are part of the ecosystem.

On 27 February 2015 at 09:41, derekrazo <notifications@github.com> wrote:

> Sounds good to me - go for it I reckon
> ᐧ
>
> On Thu, Feb 26, 2015 at 3:56 PM, Mikey the human <notifications@github.com
> >
> wrote:
>
> > i propose we migrate the cobudget-* repos from the open-app org to the
> > cobudget org, which means this top-level repo stays here. the reasoning
> > is that it's nice to have all the repos related to a project in one org
> > (including when we fork other repos for use in our project), but i'd
> rather
> > we not pollute the shared org of open-app (which i see as a place where
> > many independent projects can put their top-level repos, thus building a
> > network of projects connected together in spirit).
> >
> > how do we feel about this @derekrazo <https://github.com/derekrazo>
> > @jonlemmon <https://github.com/jonlemmon> @joshuavial
> > <https://github.com/joshuavial>?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/open-app/cobudget/issues/76>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/open-app/cobudget/issues/76#issuecomment-76267090>.
>



-- 

<http://enspiral.com/>        *Joshua Vial      *
*Phone *+33 78 30 72 875
*Phone* +64 21 684 495
*Skype  *joshuavial *Website *www.enspiral.com
*Twitter  * @joshuavial <http://twitter.com/joshuavial>

**Comment by ahdinosaur** [comment]
done. :tiger2: we can continue to define the role of the open-app org, i'm open to either way (having a open-app/cobudget repo or a open-app/core which links to cobudget), in any case i feel good about having a cobudget org now.
