### ISSUE TITLE
Q: should admin be able to update old rounds?

### ISSUE THREAD

**Issue by ahdinosaur** [open-app/cobudget#84]
@euglazer and i stumbled upon that the UI allows you to attempt to create buckets in previous rounds, but the API errors, so i just wanted to bring up the question of what is the expected functionality.

**Comment by derekrazo** [comment]
Really interesting question. Tricky because it doesn't necessarily make sense for you to retroactively update rounds, but an admin needs to be able to make changes. I'd say for now, no buckets in previous rounds. Let's talk about it in the next sprint planning though.

<3
